-- Step 1: Create database and schemas
CREATE DATABASE IF NOT EXISTS FOOD_DELIVERY_DB;
USE DATABASE FOOD_DELIVERY_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
