-- Step 3: Create invalid-order and clean-order views
USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE VIEW INVALID_ORDERS AS
SELECT
    o.ORDER_ID,
    CASE
        WHEN o.ORDER_AMOUNT <= 0 THEN 'ORDER_AMOUNT must be greater than 0'
        WHEN o.ORDER_STATUS NOT IN ('PLACED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED') THEN 'ORDER_STATUS is invalid'
        WHEN NOT EXISTS (SELECT 1 FROM RAW.RESTAURANTS r WHERE r.RESTAURANT_ID = o.RESTAURANT_ID) THEN 'RESTAURANT_ID does not exist in RAW.RESTAURANTS'
        WHEN o.ORDER_STATUS = 'DELIVERED' AND o.DELIVERY_MINUTES IS NULL THEN 'DELIVERED orders must have DELIVERY_MINUTES'
        ELSE 'UNKNOWN_VALIDATION_ISSUE'
    END AS VALIDATION_ISSUE,
    o.ORDER_AMOUNT,
    o.ORDER_STATUS,
    o.RESTAURANT_ID
FROM RAW.FOOD_ORDERS o
WHERE o.ORDER_AMOUNT <= 0
   OR o.ORDER_STATUS NOT IN ('PLACED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')
   OR NOT EXISTS (SELECT 1 FROM RAW.RESTAURANTS r WHERE r.RESTAURANT_ID = o.RESTAURANT_ID)
   OR (o.ORDER_STATUS = 'DELIVERED' AND o.DELIVERY_MINUTES IS NULL);

CREATE OR REPLACE VIEW CLEAN_ORDERS AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.RESTAURANT_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT,
    o.DELIVERY_FEE,
    o.DISCOUNT_AMOUNT,
    o.ORDER_STATUS,
    o.PAYMENT_METHOD,
    o.DELIVERY_MINUTES,
    (o.ORDER_AMOUNT + o.DELIVERY_FEE - o.DISCOUNT_AMOUNT) AS NET_ORDER_VALUE,
    r.RESTAURANT_NAME,
    r.CITY AS RESTAURANT_CITY,
    r.CUISINE_TYPE,
    r.RATING
FROM (
    SELECT fo.*, ROW_NUMBER() OVER (PARTITION BY fo.ORDER_ID ORDER BY fo.ORDER_DATE) AS rn
    FROM RAW.FOOD_ORDERS fo
) o
JOIN RAW.RESTAURANTS r ON o.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN STAGING.INVALID_ORDERS i ON o.ORDER_ID = i.ORDER_ID
WHERE o.rn = 1
  AND i.ORDER_ID IS NULL;
