-- Step 4: Create analytics views
USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW RESTAURANT_PERFORMANCE AS
SELECT
    c.RESTAURANT_ID,
    c.RESTAURANT_NAME,
    SUM(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN c.NET_ORDER_VALUE ELSE 0 END) AS TOTAL_DELIVERED_REVENUE,
    COUNT(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN 1 END) AS DELIVERED_ORDER_COUNT,
    COUNT(CASE WHEN c.ORDER_STATUS = 'CANCELLED' THEN 1 END) AS CANCELLED_ORDER_COUNT,
    AVG(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN c.DELIVERY_MINUTES END) AS AVERAGE_DELIVERY_MINUTES,
    AVG(c.RATING) AS AVERAGE_RESTAURANT_RATING
FROM STAGING.CLEAN_ORDERS c
GROUP BY c.RESTAURANT_ID, c.RESTAURANT_NAME;

CREATE OR REPLACE VIEW KPI_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_ORDERS,
    SUM(CASE WHEN ORDER_STATUS = 'DELIVERED' THEN NET_ORDER_VALUE ELSE 0 END) AS TOTAL_DELIVERED_REVENUE,
    COUNT(CASE WHEN ORDER_STATUS = 'CANCELLED' THEN 1 END) AS TOTAL_CANCELLED_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS_SERVED,
    AVG(ORDER_AMOUNT) AS AVERAGE_ORDER_VALUE,
    AVG(CASE WHEN ORDER_STATUS = 'DELIVERED' THEN DELIVERY_MINUTES END) AS AVERAGE_DELIVERY_TIME_MINUTES
FROM STAGING.CLEAN_ORDERS;
