-- Step 5: Analytical queries
USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA ANALYTICS;

-- Validation: confirm that the clean view has no duplicate order IDs
SELECT
    COUNT(*) AS DUPLICATE_ORDER_ID_COUNT
FROM (
    SELECT ORDER_ID
    FROM STAGING.CLEAN_ORDERS
    GROUP BY ORDER_ID
    HAVING COUNT(*) > 1
) d;

-- Query 1: Revenue by restaurant
SELECT
    RESTAURANT_NAME,
    SUM(NET_ORDER_VALUE) AS TOTAL_REVENUE
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'DELIVERED'
GROUP BY RESTAURANT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Query 2: Orders by status
SELECT
    ORDER_STATUS,
    COUNT(*) AS ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
GROUP BY ORDER_STATUS
ORDER BY ORDER_COUNT DESC;

-- Query 3: Average delivery time
SELECT
    AVG(DELIVERY_MINUTES) AS AVERAGE_DELIVERY_MINUTES,
    COUNT(*) AS DELIVERED_ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'DELIVERED';

-- Query 4: Cancelled orders by restaurant
SELECT
    RESTAURANT_NAME,
    COUNT(*) AS CANCELLED_ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'CANCELLED'
GROUP BY RESTAURANT_NAME
ORDER BY CANCELLED_ORDER_COUNT DESC;

-- Query 5: Top 3 customers by spending
WITH customer_totals AS (
    SELECT
        CUSTOMER_ID,
        SUM(NET_ORDER_VALUE) AS TOTAL_SPEND
    FROM STAGING.CLEAN_ORDERS
    GROUP BY CUSTOMER_ID
)
SELECT
    c.CUSTOMER_NAME,
    ct.TOTAL_SPEND
FROM customer_totals ct
JOIN RAW.CUSTOMERS c
    ON ct.CUSTOMER_ID = c.CUSTOMER_ID
ORDER BY ct.TOTAL_SPEND DESC
LIMIT 3;
