-- Five analytical queries for food delivery analytics

USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA ANALYTICS;

-- Query 1: Revenue by Restaurant
SELECT
    RESTAURANT_NAME,
    SUM(NET_ORDER_VALUE) AS TOTAL_REVENUE
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'DELIVERED'
GROUP BY RESTAURANT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Query 2: Orders by Status
SELECT
    ORDER_STATUS,
    COUNT(*) AS ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
GROUP BY ORDER_STATUS
ORDER BY ORDER_COUNT DESC;

-- Query 3: Average Delivery Time
SELECT
    AVG(DELIVERY_MINUTES) AS AVERAGE_DELIVERY_MINUTES,
    COUNT(*) AS DELIVERED_ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'DELIVERED';

-- Query 4: Cancelled Orders Count by Restaurant
SELECT
    RESTAURANT_NAME,
    COUNT(*) AS CANCELLED_ORDER_COUNT
FROM STAGING.CLEAN_ORDERS
WHERE ORDER_STATUS = 'CANCELLED'
GROUP BY RESTAURANT_NAME
ORDER BY CANCELLED_ORDER_COUNT DESC;

-- Query 5: Top 3 Customers by Spending
WITH customer_totals AS (
    SELECT
        CUSTOMER_ID,
        SUM(NET_ORDER_VALUE) AS TOTAL_SPEND
    FROM STAGING.CLEAN_ORDERS
    GROUP BY CUSTOMER_ID
)
SELECT
    c.CUSTOMER_NAME,
    ct.TOTAL_SPEND
FROM customer_totals ct
JOIN RAW.CUSTOMERS c
    ON ct.CUSTOMER_ID = c.CUSTOMER_ID
ORDER BY ct.TOTAL_SPEND DESC
LIMIT 3;
