-- Snowflake SQL to create STAGING.CLEAN_ORDERS

USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE VIEW CLEAN_ORDERS AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.RESTAURANT_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT,
    o.DELIVERY_FEE,
    o.DISCOUNT_AMOUNT,
    o.ORDER_STATUS,
    o.PAYMENT_METHOD,
    o.DELIVERY_MINUTES,
    (o.ORDER_AMOUNT + o.DELIVERY_FEE - o.DISCOUNT_AMOUNT) AS NET_ORDER_VALUE,
    r.RESTAURANT_NAME,
    r.CITY AS RESTAURANT_CITY,
    r.CUISINE_TYPE,
    r.RATING
FROM (
    SELECT
        fo.*,
        ROW_NUMBER() OVER (PARTITION BY fo.ORDER_ID ORDER BY fo.ORDER_DATE) AS rn
    FROM RAW.FOOD_ORDERS fo
) o
JOIN RAW.RESTAURANTS r
    ON o.RESTAURANT_ID = r.RESTAURANT_ID
LEFT JOIN STAGING.INVALID_ORDERS i
    ON o.ORDER_ID = i.ORDER_ID
WHERE o.rn = 1
  AND i.ORDER_ID IS NULL;
