-- Snowflake SQL to create ANALYTICS.KPI_SUMMARY

USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW KPI_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_ORDERS,
    SUM(CASE WHEN ORDER_STATUS = 'DELIVERED' THEN NET_ORDER_VALUE ELSE 0 END) AS TOTAL_DELIVERED_REVENUE,
    COUNT(CASE WHEN ORDER_STATUS = 'CANCELLED' THEN 1 END) AS TOTAL_CANCELLED_ORDERS,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS_SERVED,
    AVG(ORDER_AMOUNT) AS AVERAGE_ORDER_VALUE,
    AVG(CASE WHEN ORDER_STATUS = 'DELIVERED' THEN DELIVERY_MINUTES END) AS AVERAGE_DELIVERY_TIME_MINUTES
FROM STAGING.CLEAN_ORDERS;
