-- Snowflake SQL to create ANALYTICS.RESTAURANT_PERFORMANCE

USE DATABASE FOOD_DELIVERY_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW RESTAURANT_PERFORMANCE AS
SELECT
    c.RESTAURANT_ID,
    c.RESTAURANT_NAME,
    SUM(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN c.NET_ORDER_VALUE ELSE 0 END) AS total_delivered_revenue,
    COUNT(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN 1 END) AS delivered_order_count,
    COUNT(CASE WHEN c.ORDER_STATUS = 'CANCELLED' THEN 1 END) AS cancelled_order_count,
    AVG(CASE WHEN c.ORDER_STATUS = 'DELIVERED' THEN c.DELIVERY_MINUTES END) AS average_delivery_minutes,
    AVG(c.RATING) AS average_restaurant_rating
FROM STAGING.CLEAN_ORDERS c
GROUP BY
    c.RESTAURANT_ID,
    c.RESTAURANT_NAME
ORDER BY total_delivered_revenue DESC;
