-- Sample Snowflake SQL script to create a database, schema, and table
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE SAMPLE_DB;
CREATE OR REPLACE SCHEMA SAMPLE_DB.PUBLIC;

CREATE OR REPLACE TABLE SAMPLE_DB.PUBLIC.CUSTOMERS (
    CUSTOMER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO SAMPLE_DB.PUBLIC.CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL)
VALUES
    ('Alice', 'Johnson', 'alice@example.com'),
    ('Bob', 'Smith', 'bob@example.com'),
    ('Carol', 'Davis', 'carol@example.com');

SELECT * FROM SAMPLE_DB.PUBLIC.CUSTOMERS ORDER BY CUSTOMER_ID;
